/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#c7c6ca",
        "error-container": "#93000a",
        "inverse-primary": "#3f4cda",
        "on-surface-variant": "#c6c5d7",
        "surface-container-highest": "#343538",
        "surface-tint": "#bec2ff",
        "on-secondary": "#2f3033",
        "error": "#ffb4ab",
        "surface-variant": "#343538",
        "surface-container": "#1f1f23",
        "surface-dim": "#121316",
        "surface": "#121316",
        "on-secondary-container": "#b9b8bc",
        "surface-container-high": "#292a2d",
        "surface-bright": "#38393c",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#bec2ff",
        "secondary-fixed-dim": "#c7c6ca",
        "secondary-fixed": "#e3e2e6",
        "on-primary-fixed": "#000569",
        "tertiary-container": "#727578",
        "on-background": "#e3e2e6",
        "tertiary": "#c4c7ca",
        "surface-container-lowest": "#0d0e11",
        "primary-fixed": "#e0e0ff",
        "on-primary-container": "#fffdff",
        "inverse-surface": "#e3e2e6",
        "inverse-on-surface": "#2f3033",
        "tertiary-fixed-dim": "#c4c7ca",
        "on-tertiary-fixed": "#191c1e",
        "tertiary-fixed": "#e1e3e6",
        "on-tertiary-fixed-variant": "#44474a",
        "on-tertiary-container": "#fcfdff",
        "background": "#121316",
        "primary-container": "#5865f2",
        "on-surface": "#e3e2e6",
        "outline-variant": "#454655",
        "secondary-container": "#48494c",
        "on-secondary-fixed": "#1a1b1e",
        "on-primary": "#000da4",
        "on-tertiary": "#2d3133",
        "on-error": "#690005",
        "surface-container-low": "#1a1b1e",
        "primary": "#bec2ff",
        "outline": "#8f8fa0",
        "on-primary-fixed-variant": "#222fc2",
        "on-secondary-fixed-variant": "#46474a"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "inter": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
